create table notification_settings (
    id serial,
	person_id int4,
    notification_type notification_code_type,
    enable boolean,
    primary key (id)
);

insert into notification_settings (person_id, notification_type, enable) values
    ( 1, 'POST', 'true'),
    ( 1, 'POST_COMMENT', 'true'),
    ( 1, 'COMMENT_COMMENT', 'true'),
    ( 1, 'FRIEND_REQUEST', 'true'),
    ( 1, 'MESSAGE', 'true'),
    ( 2, 'POST', 'true'),
    ( 2, 'POST_COMMENT', 'true'),
    ( 2, 'COMMENT_COMMENT', 'true'),
    ( 2, 'FRIEND_REQUEST', 'true'),
    ( 2, 'MESSAGE', 'true'),
    ( 3, 'POST', 'true'),
    ( 3, 'POST_COMMENT', 'true'),
    ( 3, 'COMMENT_COMMENT', 'true'),
    ( 3, 'FRIEND_REQUEST', 'true'),
    ( 3, 'MESSAGE', 'true'),
    ( 4, 'POST', 'true'),
    ( 4, 'POST_COMMENT', 'true'),
    ( 4, 'COMMENT_COMMENT', 'true'),
    ( 4, 'FRIEND_REQUEST', 'true'),
    ( 4, 'MESSAGE', 'true'),
    ( 5, 'POST', 'true'),
    ( 5, 'POST_COMMENT', 'true'),
    ( 5, 'COMMENT_COMMENT', 'true'),
    ( 5, 'FRIEND_REQUEST', 'true'),
    ( 5, 'MESSAGE', 'true'),
    ( 6, 'POST', 'true'),
    ( 6, 'POST_COMMENT', 'true'),
    ( 6, 'COMMENT_COMMENT', 'true'),
    ( 6, 'FRIEND_REQUEST', 'true'),
    ( 6, 'MESSAGE', 'true');